apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
    srv: api
spec:
  selector:
    srv: api
  type: NodePort
  ports:
   - name: react
     port: 30000
     nodePort: 30000
   - name: express
     port: 30001
     nodePort: 30001
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    srv: api
  name: securitization-pod
spec:
  containers:
    - name: securitization-blockchain
      image: kkbankol/securitization-blockchain
      imagePullPolicy: Always
      stdin: true
      tty: true
      args: ["-c", "cd /root/securitization_blockchain/sc-ui && PORT=30000 npm start | PORT=30001 node react-backend/bin/www"]
